### ISSUE TITLE
[WIP]RFC: 新站点

### ISSUE THREAD

**Issue by alvinhui** [appworks-lab/TSC#2]
### 信息结构

- 导航：
    - 工具箱(toolkit)：跳转到文档
    - 研发套件(pack)：跳转到文档
    - 物料(material)：
        - 区块：跳转到页面
        - 模板：跳转到页面
        - 自定义：跳转到文档
- 主区：
    - Logo
    - 名称
    - slogan
- 产品
    - 工具箱
    - 研发套件
    - 物料
- 谁在使用 
- 页尾
     - 社区
     - 帮助
     - 更多

### 示意图

![image](https://user-images.githubusercontent.com/4392234/117629302-9bb8c180-b1ac-11eb-8d81-5fac0a45cc9a.png)

**Comment by fyangstudio** [comment]
参考 IntelliJ 官网思路？
https://www.jetbrains.com/

再分出 toolkit 和 套件 2个产品页？

**Comment by alvinhui** [comment]
- 关于研发套件
- 快速开始：创建项目/安装依赖/启动调试/发布项目
- 项目创建与发布：模板创建/配置创建/DEF 发布
- 工程辅助：调试预览/依赖管理
- 编码辅助：
  - 代码自动补全
  - 代码重构
  - 框架和库的 API 升级
- 可视化辅助
  - 物料可视化：使用模板/使用页面/使用区块/使用组件/自定义物料
  - 可视化搭建和配置可视化
- 编码质效
  - 编码行为追踪
  - 代码质量评测

**Comment by fyangstudio** [comment]
仓库：https://github.com/appworks-lab/appworks-lab.github.io
分支合并到 master 时站点会自动部署。

定制展示组件用 react 开发，放 src 下。
文档集中在 docs 目录下管理

地址：https://appworks-lab.github.io/

**Comment by imsobear** [comment]
## 研发套件大纲

- 关于研发套件 
- 快速开始：安装套件/创建项目/启动调试 
- FAQ：下载物料失败、xxx

### 基础教程

- 创建项目
- 调试与发布：安装依赖、启动调试、预览、项目发布、依赖管理
- 物料使用：官方物料、自定义物料、模板/区块/组件如何使用
- 代码补全：样式代码、json、js 项目
- 代码重构

### 高阶指南

- 项目质量：lint 规范、执行 Doctor、报告、修复
- 研发数据：Time Master

**Comment by fyangstudio** [comment]
### 基础教程

* 环境准备

**Comment by fyangstudio** [comment]
![编组 4](https://user-images.githubusercontent.com/9896768/118610885-d515b080-b7ee-11eb-8a7f-2eede70065ba.png)
